/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Story = IDL.Record({
  'title' : IDL.Text,
  'description' : IDL.Text,
  'audioUrl' : IDL.Text,
  'author' : IDL.Text,
  'durationSeconds' : IDL.Nat,
  'category' : IDL.Text,
});

export const idlService = IDL.Service({
  'getAllCategories' : IDL.Func([], [IDL.Vec(IDL.Text)], ['query']),
  'getAllStories' : IDL.Func([], [IDL.Vec(Story)], ['query']),
  'getFeaturedStory' : IDL.Func([], [Story], ['query']),
  'getMotivationalQuote' : IDL.Func([], [IDL.Text], ['query']),
  'getStoriesByCategory' : IDL.Func([IDL.Text], [IDL.Vec(Story)], ['query']),
  'getStoryByTitle' : IDL.Func([IDL.Text], [Story], ['query']),
  'setMotivationalQuote' : IDL.Func([IDL.Text], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Story = IDL.Record({
    'title' : IDL.Text,
    'description' : IDL.Text,
    'audioUrl' : IDL.Text,
    'author' : IDL.Text,
    'durationSeconds' : IDL.Nat,
    'category' : IDL.Text,
  });
  
  return IDL.Service({
    'getAllCategories' : IDL.Func([], [IDL.Vec(IDL.Text)], ['query']),
    'getAllStories' : IDL.Func([], [IDL.Vec(Story)], ['query']),
    'getFeaturedStory' : IDL.Func([], [Story], ['query']),
    'getMotivationalQuote' : IDL.Func([], [IDL.Text], ['query']),
    'getStoriesByCategory' : IDL.Func([IDL.Text], [IDL.Vec(Story)], ['query']),
    'getStoryByTitle' : IDL.Func([IDL.Text], [Story], ['query']),
    'setMotivationalQuote' : IDL.Func([IDL.Text], [], []),
  });
};

export const init = ({ IDL }) => { return []; };